spring:
    datasource:
        url: jdbc:postgresql://db.lfvjoiwqvgvcvljfyngk.supabase.co:5432/postgres?sslmode=require
        username: postgres
        password: lamesa505052@

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none 
        properties:
            hibernate:
                format_sql: true
                default_schema: public
            

server:
  port: 8080
